---
workspace:
  base: /go
  path: src/github.com/NYTimes/drone-gke

build_config: &config
  image: golang:1.9
  environment:
    - CGO_ENABLED=0
  commands:
    - go build -a -ldflags "-X main.version=${DRONE_TAG:-0.8} -X main.rev=${DRONE_COMMIT}"

pipeline:
  test:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover

  build:
    <<: *config
    when:
      branch:
        - develop
        - master

  build_release:
    <<: *config
    when:
      event: tag

  publish_develop:
    image: plugins/docker
    repo: nytimes/drone-gke
    tag:
      - "develop"
    secrets:
      - docker_username
      - docker_password
    when:
      event: push
      branch: develop

  publish_latest:
    image: plugins/docker
    repo: nytimes/drone-gke
    tag:
      - "latest"
      - "0.8"
    secrets:
      - docker_username
      - docker_password
    when:
      event: push
      branch: master

  publish_release:
    image: plugins/docker
    repo: nytimes/drone-gke
    tag:
      - "${DRONE_TAG}"
    secrets:
      - docker_username
      - docker_password
    when:
      event: tag

  slack:
    image: plugins/slack
    channel: dv-notifications
    secrets:
      - slack_webhook
    when:
      branch:
        - develop
        - master

  slack_tag:
    image: plugins/slack
    channel: dv-notifications
    secrets:
      - slack_webhook
    when:
      event:
        - tag
