---
workspace:
  base: /go
  path: src/github.com/NYTimes/drone-gke

build_config: &build_config
  image: golang:1.10
  environment:
    - CGO_ENABLED=0
  commands:
    - go build -a -ldflags "-X main.version=${DRONE_TAG:-0.8} -X main.rev=${DRONE_COMMIT}"

publish_config: &publish_config
  image: plugins/docker
  repo: nytimes/drone-gke
  secrets:
    - docker_username
    - docker_password

pipeline:
  test:
    image: golang:1.10
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover

  build:
    <<: *build_config
    when:
      branch:
        - develop
        - master

  build_release:
    <<: *build_config
    when:
      event: tag

  publish_develop:
    <<: *publish_config
    tag:
      - "develop"
    when:
      event: push
      branch: develop

  publish_latest:
    <<: *publish_config
    auto_tag: true

  publish_1_8:
    <<: *publish_config
    auto_tag: true
    auto_tag_suffix: "1.8"
    dockerfile: Dockerfile.1.8

  publish_1_9:
    <<: *publish_config
    auto_tag: true
    auto_tag_suffix: "1.9"
    dockerfile: Dockerfile.1.9

  slack:
    image: plugins/slack
    channel: dv-notifications
    secrets:
      - slack_webhook
    when:
      branch:
        - develop
        - master

  slack_tag:
    image: plugins/slack
    channel: dv-notifications
    secrets:
      - slack_webhook
    when:
      event:
        - tag
