---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: {{.app_name}}-{{.env}}

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{.app_name}}
        env: {{.env}}
    spec:
      containers:
        - name: app
          image: {{.app_image}}
          ports:
            - containerPort: 8080
          env:
            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.app_name}}-{{.env}}
                  key: app-api-key
---
apiVersion: v1
kind: Service

metadata:
  name: {{.app_name}}-{{.env}}

spec:
  type: LoadBalancer
  selector:
    app: {{.app_name}}
    env: {{.env}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
